#!/usr/bin/env bash
# FILE: bless_user.sh
################################################################################
# Example INVOKE:
# bless_user -f id_rsa.pub -r root@198.211.108.237
################################################################################
# {{{ Debugging Lines
# vim: foldmethod=marker
set -u # exit upon unset vars
set -e # exit upon first-error
set -o pipefail # exit
# trap read debug

## For simulating function-runs
## > set argone argtwo argthree
# PROMPT_COMMAND='echo "\ Args are: $@ #: $#"'

## ALTERNATIVE TO BASH-DB
# exec 5> >(logger -t $0)
# BASH_XTRACEFD="5"
PS4='$LINENO: '
# set -x # print each line of code 
# trap read debug
# error() {
#   local sourcefile=$1
#   local lineno=$2
#   # ...logic for reporting an error at line $lineno
#   #    of file $sourcefile goes here...
#}
#trap 'error "${BASH_SOURCE}" "${LINENO}"' ERR
# https://stackoverflow.com/questions/10743026/how-to-display-last-command-that-failed-when-using-bash-set-e
# }}}
################################################################################
#{{{ c_color codes
c_red='\033[0;31m'
c_nc='\033[0m'
c_pink='\033[0;35m'
#}}}
################################################################################
#{{{ Variable declarations
DEBUG_MODE=NO
VERBOSE_MODE=NO
HOST_TO_BE_AUTHED=NONE
VERIFY_MODE=NO
#}}}
################################################################################
#{{{ USAGE
_help_msg() {
    if [ $# -ne 0 ]; then
        printf "$c_red"
        echo "UNKNOWN ARGs:" "$@"
        printf "$c_nc"
    fi
    _usage
}

_usage() {
    echo "usage: $0 [...] <HOST_STRING>"
    echo '
        # How to get string?
         -k, --key      "<RAW_KEY_STRING>"
         -f, --file     <PATH_TO_KEY>
         -g, --github   <GITHUB_NAME>
         -s, --server   <SSH_STRING>

        # Which user on the remote system?
         -u, --username  <USERNAME_TO_BLESS>
         -r, --root          (just auth for root)

        # How to connect to the system, in order to bless?
         -h, --host     <HOST_STRING>
         -p, --port     <SSHD_PORT>

        # Debugging
         -d, --debug    Dont execute, just print values
         -v, --verify   See if key/user is verified already
         --verbose      Verbose; execute & print values

'
}
#}}}
################################################################################
#{{{ ARG-PROC HELPER FUNCTIONS:
from_gh() {
    curl "https://github.com/${1}.keys"
    # -s for stderr-silent
}
from_file() {
    if ! [ -f "$1" ]; then # assume it is in sshdir
        cat "$HOME/.ssh/$1"
    else
        cat "$1"
    fi
}
from_server() {
    ssh $1 'cat ~/.ssh/id_rsa.pub'
}
#}}}
################################################################################
#{{{ ARG PROCESSING:
################################################################################

ORIGINAL_POSITIONAL=()
while [[ $# -gt 0 ]]
do
flag="$1"

case $flag in
    # How to get the pubkey-data?
    -k|--key)
    PUBKEYSTRING="${2:?${flag} requires a second argument.$'\n\n'"$(_help_msg)"}"
    shift # past argument
    shift # past value
    ;;
    -f|--file)
    PUBKEYFILE="${2:?${flag} requires a second argument.$'\n\n'"$(_help_msg)"}"
    shift # past argument
    shift # past value
    PUBKEYSTRING=$( from_file "$PUBKEYFILE" ) || exit 1
    ;;
    -g|--github*)
    GITHUB_NAME="${2:?${flag} requires a second argument.$'\n\n'"$(_help_msg)"}"
    shift # past argument
    shift # past value
    PUBKEYSTRING=$( from_gh "$GITHUB_NAME" ) || exit 1
    ;;
    -s|--server)
    HOST_TO_BE_AUTHED="${2:?${flag} requires a second argument.$'\n\n'"$(_help_msg)"}"
    shift # past argument
    shift # past value
    PUBKEYSTRING=$( from_server "$HOST_TO_BE_AUTHED" ) || exit 1
    ;;

    # HOW to AUTHENTICATE the key
    # ... this can also just be the last arg, using ssh-config to find the params
    # ... these are args to pass-off to ssh
    -h|--host) #either a hostname, or ip-address
    echo -- "$flag is not yet implemented" && exit 1
    HOST="$2"
    shift
    shift
    ;;
    -p|--port)
    echo -- "$flag is not yet implemented" && exit 1
    SSHD_PORT="$2"
    shift
    shift
    ;;

    # WHAT to AUTHENTICATE the key as
    -r|--root)
    echo -- "$flag is not yet implemented" && exit 1
    ROOT_AUTH=YES
    shift # past argument
    ;;
    -u|--username)
    echo -- "$flag is not yet implemented" && exit 1
    USER_AUTH="$2"
    shift
    shift
    ;;

    # etc.
    -d|--debug) # just print the assigned vars, DONT execute main
    DEBUG_MODE=YES
    VERBOSE_MODE=YES
    shift
    ;;
    --verbose) # execute main, but also print values
    VERBOSE_MODE=YES
    shift
    ;;
    -v|--verify)
    VERIFY_MODE=YES
    shift
    ;;
    --help)
    _usage
    exit 0
    ;;

    *)    # UNKNOWN option, or LAST
    if [ $# -gt 1 ]; then # it is NOT LAST ARG, so error
        UNKNOWN_ARGS+=("$1") # save it in an array for later
        shift # past argument
    else 
        SSH_STRING="$1"
        shift
    fi
    ;;
esac
done

set -- "${ORIGINAL_POSITIONAL[@]}" # restore positional parameters

# VERBOSE MODE: print the values of the processed params
printvar() { #{{{
    printf "$c_pink"
    printf "${1}="
    printf "$c_nc"
    echo "${!1}"
} #}}}
set +u # prevent unbound vars from causing exit
if [[ $VERBOSE_MODE == YES ]]; then
    varnames="
PUBKEYSTRING
PUBKEYFILE
GITHUB_NAME
HOST
SSHD_PORT
ROOT_AUTH
USER_AUTH
DEBUG_MODE
SSH_STRING
HOST_TO_BE_AUTHED
"
    for varname in $varnames; do
        printvar "$varname"
    done

    echo "Args remaining:" "$@" "\$#: $#"
    echo bash version: $BASH_VERSION
################################################################################
fi
set -u # turn strict-mode back on


################################################################################
# If invoked with unknown parameters, fail-out
set +u
if [ ${#UNKNOWN_ARGS} -ne 0 ]; then
    _help_msg "${UNKNOWN_ARGS[@]}"
    exit 1
fi
set -u
#}}}
################################################################################
#{{{ FUNCTIONS: for helping main
view_remote_authorized_keys() {
    ssh $SSH_STRING '
    echo -e "\033[0;35m"
    echo AUTHORIZED KEYS FILE CONTENTS, NOW:
    echo -e "\033[0;m"
    cat $HOME/.ssh/authorized_keys | nl
    echo 
    '
}

#}}}
################################################################################
#{{{ MAIN
main() {
    # 0. To verify?
    if [[ $VERIFY_MODE = YES ]]; then
        tput rmam ; printf %b '\033[?7l' # wrapoff
        view_remote_authorized_keys || {
        LEC=$?
        tput smam ; printf %b '\033[?7h' # wrapon
        exit $LEC
    }
        tput smam ; printf %b '\033[?7h' # wrapon
    # Verify complete
    exit 0
    fi

    # 1. Check that key data has been defined
    if [[ -z $PUBKEYSTRING ]]; then
        error "No key data defined; must supply either -f/-k/-g."
        _help_msg
    fi

    # Write the key to the authorization file
    echo "$PUBKEYSTRING" | ssh $SSH_STRING '
    umask 0077; 
    mkdir -p $HOME/.ssh; 
    cat >> $HOME/.ssh/authorized_keys;
    ' || exit $?

    # Now view the keys 
    view_remote_authorized_keys || exit $?

}

if ! [[ "$DEBUG_MODE" = YES ]]; then
    main || {
        main_exit_code=$?
        _help_msg
        exit $main_exit_code
    }
else
    exit 1
fi
#}}}

################################################################################
echo END OF SCRIPT
exit 9
################################################################################
